* Urban ecology has meant
** understanding why things are where there are
*** City wide perspective
**** Burgess
     This is largely descriptive. The center expands, this encroaches
     on previous uses in ways that are status polluting or otherwise
     incompatible driving them out.  Not a lot of clear theory
**** Central place     
     The central place has the most access to most of the city and
     lowest overall travel time costs. Different uses compete for
     this location, commerce wins. Differnt uses may also wish to
     trade off between centrality and other goods (classically land)
     so the wealthy, in particular may wish to be a little bit
     further away if they can have larger houses (Alonso)
**** Cellular development
     Industry locates in places that are nodes for fast
     transit. Usually not in the central city. Workers live around
     industry.
**** Sectoral
     Geographic expansion of population increasing city is driving by
     speculation and the most valuable developments are adjacent to
     current high status places leading to sectoral development from
     central node
**** Dominance
     The location of commanding functions in the center effects the
     types of organizations and functions that appear quite a long,
     long way away. Well outside municipal boundaries.
**** Criticisms
     Lots of examples of people not doing any of these things,
     particular seeming to most efficiently allocate uses according
     to central place theory. 
*** Cluster explanations are often very local, and not scale properties
**** Effects of ecosystem on individuals
     - Niche theory
     - Neighborhood effects of raudenbusch
**** Theoretical approaches 
***** Scene effects
      In order to perform a certain kind of life people and
      businesses co locate and co-create each other in certain spaces.
      Firey, Clark, Schelling. See Taub as an example of how this
      goes wrong. Grannis
******* Firey
	Who says that people attached attributes to a place that
	facilitates other goals. resources attach the land, but those
	resrouces are the mix of current uses themselves. Yogi Berra
***** Craft effects
      In non routinized businesses there needs to be a great deal of
      communication specialized interactions that is facilitated by
      propinquity. Creative work, always has this element. This global
      cities of Saskia Sassen and the industry clusters of Michael
      porter both have this element.
      Arises in places where the there is network of firms that have
      to interpenetrate in order to do their work, and all the work
      hasn't been brought into a single firm. 

      Richard florida argues that you get craft effects through
      attracting scenesters
*** Local/Regional/Long Distance
    What is local vs regional vs long distance depends upon
    technology. Both travel and communcation technology but also the
    technolically mediated division of labor. The requirements to go
    out into the world to fulfill needs like work, food production,
    child care, health care.. etc. This used to be done largely at
    home. Hawley
**** Understanding that local spaces are very organized, descriptively
***** Qualititatively
     Chicago school and the many, ethnogaphies and community studies
***** Quantitatively
     - Shevksy and Bell
     - Hoyt


* Three takes on ecology
** Competition
** Mutualism (Division of Labor, craft nature)
** Niche width
*** Predation
*** Mutualism

       
